name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/desktop_icon_x2.svg
  - assets/vectors/group_102_x2.svg
  - assets/images/ellipse_975.jpeg
  - assets/vectors/edit_1_x2.svg
  - assets/vectors/ellipse_9752_x2.svg
  - assets/vectors/back_3_x2.svg
  - assets/images/image_7.png
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/icon_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/iconexternal_link_2_x2.svg
  - assets/vectors/iconexternal_link_x2.svg
  - assets/images/image_22.png
  - assets/images/ellipse_975.jpeg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/iconly_light_time_circle_x2.svg
  - assets/vectors/profile_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/bag_1_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/home_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/images/ellipse_977.jpeg
  - assets/images/ellipse_976.jpeg
  - assets/images/ellipse_978.jpeg
  - assets/images/image_22.png
  - assets/images/ellipse_975.jpeg
  - assets/images/ellipse_980.jpeg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/profile_15_x2.svg
  - assets/vectors/plus_21_x2.svg
  - assets/vectors/group_103_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/plus_1_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/plus_8_x2.svg
  - assets/vectors/plus_11_x2.svg
  - assets/vectors/plus_15_x2.svg
  - assets/vectors/bag_2_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/ellipse_9801_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/home_2_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/ellipse_981_x2.svg
  - assets/vectors/plus_4_x2.svg
  - assets/images/ellipse_975.jpeg
  - assets/vectors/profile_12_x2.svg
  - assets/vectors/stroke_113_x2.svg
  - assets/vectors/stroke_110_x2.svg
  - assets/vectors/stroke_12_x2.svg
  - assets/vectors/ellipse_9751_x2.svg
  - assets/vectors/danger_circle_x2.svg
  - assets/vectors/stroke_18_x2.svg
  - assets/vectors/back_1_x2.svg
  - assets/vectors/document_1_x2.svg
  - assets/vectors/group_427322196_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/stroke_115_x2.svg
  - assets/vectors/profile_10_x2.svg
  - assets/vectors/stroke_17_x2.svg
  - assets/vectors/stroke_15_x2.svg
  - assets/vectors/profile_6_x2.svg
  - assets/vectors/profile_1_x2.svg
  - assets/vectors/profile_3_x2.svg
  - assets/vectors/stroke_14_x2.svg
  - assets/vectors/stroke_19_x2.svg
  - assets/vectors/profile_11_x2.svg
  - assets/vectors/stroke_114_x2.svg
  - assets/vectors/stroke_112_x2.svg
  - assets/vectors/stroke_1_x2.svg
  - assets/vectors/stroke_116_x2.svg
  - assets/vectors/profile_9_x2.svg
  - assets/vectors/profile_5_x2.svg
  - assets/vectors/profile_17_x2.svg
  - assets/vectors/profile_14_x2.svg
  - assets/vectors/back_6_x2.svg
  - assets/vectors/group_10_x2.svg
  - assets/images/logo.png
  - assets/vectors/group_101_x2.svg
  - assets/vectors/back_5_x2.svg
  - assets/vectors/plus_5_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/logosmastercard_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/images/image_7.png
  - assets/vectors/plus_12_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/back_x2.svg
  - assets/images/image_23.png
  - assets/images/image_223.png
  - assets/images/image_221.png
  - assets/images/image_222.png
  - assets/images/image_22.png
  - assets/images/ellipse_975.jpeg
  - assets/vectors/plus_10_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/plus_6_x2.svg
  - assets/vectors/plus_18_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/home_3_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/bag_3_x2.svg
  - assets/vectors/profile_18_x2.svg
  - assets/vectors/plus_20_x2.svg
  - assets/vectors/plus_7_x2.svg
  - assets/vectors/swap_2_x2.svg
  - assets/vectors/plus_3_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/images/image_22.png
  - assets/images/ellipse_975.jpeg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/profile_4_x2.svg
  - assets/vectors/swap_x2.svg
  - assets/vectors/plus_19_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/plus_17_x2.svg
  - assets/vectors/plus_22_x2.svg
  - assets/vectors/plus_9_x2.svg
  - assets/vectors/home_1_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/plus_13_x2.svg
  - assets/vectors/bag_x2.svg
  - assets/vectors/plus_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/logosmastercard_1_x2.svg
  - assets/vectors/back_4_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/plus_2_x2.svg
  - assets/images/image_221.png
  - assets/vectors/plus_16_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vec_1_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/union_5_x2.svg
  - assets/vectors/iconexternal_link_1_x2.svg
  - assets/vectors/on_2_x2.svg
  - assets/vectors/union_1_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/icon_3_x2.svg
  - assets/vectors/profile_16_x2.svg
  - assets/vectors/profile_13_x2.svg
  - assets/vectors/profile_7_x2.svg
  - assets/vectors/back_2_x2.svg
  - assets/vectors/profile_8_x2.svg
  - assets/vectors/stroke_111_x2.svg
  - assets/vectors/stroke_118_x2.svg
  - assets/vectors/stroke_117_x2.svg
  - assets/vectors/stroke_16_x2.svg

